---
title: "Data_manipulation_manuscriptBDA"
author: "Gould, Katelyn"
date: "5/1/2020"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r}
##Install packages
if ("devtools" %in% rownames(installed.packages()) == 'FALSE') install.packages('devtools') 
library(devtools)
if ("segmented" %in% rownames(installed.packages()) == 'FALSE') install.packages('segmented') 
if ("plotrix" %in% rownames(installed.packages()) == 'FALSE') install.packages('plotrix') 
if ("gridExtra" %in% rownames(installed.packages()) == 'FALSE') install.packages('gridExtra') 
if ("LoLinR" %in% rownames(installed.packages()) == 'FALSE') install_github('colin-olito/LoLinR') 
if ("lubridate" %in% rownames(installed.packages()) == 'FALSE') install.packages('lubridate') 
if ("chron" %in% rownames(installed.packages()) == 'FALSE') install.packages('chron') 
if ("plyr" %in% rownames(installed.packages()) == 'FALSE') install.packages('plyr') 
if ("dplyr" %in% rownames(installed.packages()) == 'FALSE') install.packages('dplyr') 

#Read in required libraries

##### Include Versions of libraries
#install_github('colin-olito/LoLinR')
library("ggplot2")
library("segmented")
library("plotrix")
library("gridExtra")
library("LoLinR")
library("lubridate")
library("chron")
library('plyr')
library('dplyr')
library('tidyverse')
library('xlsx')
library('dplyr')
library('tidyr')
library(readxl)
library(stringr)

```


```{r}

# get the file path

setwd("C:/Github/TPC_BDA_github")
getwd()

path.p<-"C:/Github/TPC_BDA_github/Raw_R" #the location of all your respirometry files

# bring in the respiration files
file.names<-basename(list.files(path = path.p, pattern = "csv$", recursive = TRUE)) #list all csv file names in the folder and subfolders

#basename above removes the subdirectory name from the file
file.names.full<-list.files(path = path.p, pattern = "csv$", recursive = TRUE) 

#generate a 3 column dataframe with specific column names
Photo.R<- data.frame(matrix(NA, nrow=length(file.names)*2, ncol=4))
colnames(Photo.R) <- c("fragment.ID.full","Intercept", "umol.L.sec","Temp.C")
View(Photo.R)
```

```{r}
#Change all Excel files to CSV- if you need to here is the code for it
#kate_files <- list.files("C:/Users/Kate/OneDrive - #University of North Carolina at Chapel #Hill/2019laptop/Documents/TPC_Acropora/Presens #Measurements/All", pattern="*.xlsx", full.names=TRUE)
#
#for (all in kate_files){
#  
#  n <- strsplit(all,"C:/Users/Kate/OneDrive - University of #North Carolina at Chapel #Hill/2019laptop/Documents/TPC_Acropora/Presens #Measurements/All")[[1]][2]
#  n <- paste(strsplit(n,"//.")[[1]][1],".csv", sep = "")
#  df<-read.xlsx(all, sheetIndex = 6)
#  write.csv(df, paste("C:/Users/Kate/OneDrive - University #of North Carolina at Chapel #Hill/2019laptop/Documents/TPC_Acropora/Presens #Measurements/All/csv",n, sep = ""), 
#            row.names = FALSE, quote=FALSE)
#}

```

```{r}
#Load Sample Info 
Sample.Info <- read_excel("C:/Github/TPC_BDA_github/Raw_data/Sample.Info.xlsx")#read in sample.info data
View(Sample.Info)

# load surface area data
SA <- read_excel("C:/Github/TPC_BDA_github/Raw_data/SA.xlsx") #read sample.info data
View(SA)
```


```{r}
#Calculate the volume of water
as.numeric(SA$volume.mls)
# joint the sample info and surface area and volume measurements
Sample.Info<-left_join(Sample.Info, SA)
Sample.Info$date<-NULL

View(Sample.Info)
```

```{r}
# for every file in list calculate O2 uptake or release rate and add the data to the Photo.R dataframe
for(i in 1:length(file.names.full)) { # for every file in list calculate O2 uptake or release rate and add the data to the Photo.R dataframe
  
  #find the lines in sample info that have the same file name that is being brought it
  FRow<-which(Sample.Info$fragment.ID.full==strsplit(file.names[i],'.csv'))
  # read in the O2 data one by one
  Photo.Data1 <-read.csv(file.path(path.p,file.names.full[i]), header=T) # skips the first line
  Photo.Data1 <-plyr::rename(Photo.Data1, c("Date"="Time","Oxygen"= "Value","Temperature"="Temp"))
  #rename columns 
  Photo.Data1  <- Photo.Data1[,c("Time","Value","Temp")] #subset columns of interest
  # Photo.Data1$Time <-strptime(Photo.Data1$Time, format = "%H:%M:%S") 
  Photo.Data1$Time <- strftime(Photo.Data1$Time, format = "%H:%M:%S") 
  #Photo.Data1$Time <- as.POSIXct(Photo.Data1$Time,format="%H:%M:%S", tz = "") #convert time from character to time
  Photo.Data1 <- na.omit(Photo.Data1)
  
  
  # clean up some of the data
  n<-dim(Photo.Data1)[1] # length of full data
  Photo.Data1 <-Photo.Data1[240:(n-3),] #start at data point ~4 minute in to avoid excess noise from start of run and remove last 3 lines containing text
  n<-dim(Photo.Data1)[1] #list length of trimmed data
  Photo.Data1$sec <- (1:n) #set seconds by one from start to finish of run in a new column
  
  
  #Save plot prior to and after data thinning to make sure thinning is not too extreme
  rename <- sub(".csv","", file.names[i]) # remove all the extra stuff in the file name
  
  pdf(paste0("C:/Github/TPC_BDA_github/Raw_R/Thin",rename,"thinning.pdf")) # open the graphics device
  
  par(omi=rep(0.3, 4)) #set size of the outer margins in inches
  par(mfrow=c(1,2)) #set number of rows and columns in multi plot graphic
  plot(Value ~ sec, data=Photo.Data1 , xlab='Time (seconds)', ylab=expression(paste(' O'[2],' (',mu,'mol/L)')), type='n', axes=FALSE) #plot (empty plot to fill) data as a function of time
  usr  <-  par('usr') # extract the size of the figure margins
  rect(usr[1], usr[3], usr[2], usr[4], col='grey90', border=NA) # put a grey background on the plot
  whiteGrid() # make a grid
  box() # add a box around the plot
  points(Photo.Data1 $Value ~ Photo.Data1 $sec, pch=16, col=transparentColor('dodgerblue2', 0.6), cex=1.1)
  axis(1) # add the x axis
  axis(2, las=1) # add the y-axis
  
  # Thin the data to make the code run faster
  Photo.Data.orig<-Photo.Data1#save original unthinned data
  Photo.Data1 <-  thinData(Photo.Data1 ,by=20)$newData1 #thin data by every 20 points for all the O2 values
  Photo.Data1$sec <- as.numeric(rownames(Photo.Data1 )) #maintain numeric values for time
  Photo.Data1$Temp<-NA # add a new column to fill with the thinned data
  Photo.Data1$Temp <-  thinData(Photo.Data.orig,xy = c(1,3),by=20)$newData1[,2] #thin data by every 20 points for the temp values
  
  # plot the thinned data
  plot(Value ~ sec, data=Photo.Data1 , xlab='Time (seconds)', ylab=expression(paste(' O'[2],' (',mu,'mol/L)')), type='n', axes=FALSE) #plot thinned data
  usr  <-  par('usr')
  rect(usr[1], usr[3], usr[2], usr[4], col='grey90', border=NA)
  whiteGrid()
  box()
  points(Photo.Data1 $Value ~ Photo.Data1 $sec, pch=16, col=transparentColor('dodgerblue2', 0.6), cex=1.1)
  axis(1)
  axis(2, las=1)
  ##Olito et al. 2017: It is running a bootstrapping technique and calculating the rate based on density
  #option to add multiple outputs method= c("z", "eq", "pc")
  Regs  <-  rankLocReg(xall=Photo.Data1$sec, yall=Photo.Data1$Value, alpha=0.5, method="pc", verbose=TRUE)  
  
  # add the regression data
  plot(Regs)
  dev.off()
  
  # fill in all the O2 consumption and rate data
  Photo.R[i,2:3] <- Regs$allRegs[1,c(4,5)] #inserts slope and intercept in the dataframe
  Photo.R[i,1] <- rename #stores the file name in the Date column
  Photo.R[i,4] <- mean(Photo.Data1$Temp, na.rm=T)  #stores the Temperature in the Temp.C column
  #Photo.R[i,5] <- PR[j] #stores stores whether it is photosynthesis or respiration
  
  
  # rewrite the file everytime... I know this is slow, but it will save the data that is already run

}
```


```{r}
View(Photo.R)

  
Photo.R <- na.omit(Photo.R)
  
#write.csv(Photo.R,"C:/Github/TPC_BDA_github/R_output/Manuscript/Photo.RPG.csv") 
```

```{r}

#join dataframes
Photo.R<-left_join(Photo.R, Sample.Info)
View(Photo.R)
```

```{r}
# Calculate P and R rate
#Convert sample volume to mL
Photo.R$volume <- Photo.R$volume.mls/1000 #calculate volume

#Account for chamber volume to convert from umol L-1 s-1 to umol s-1. This standardizes across water volumes (different because of coral size) and removes per Liter
Photo.R$umol.sec <- Photo.R$umol.L.sec*Photo.R$volume

#Account for blank rate by temperature
#convert character columns to factors
Photo.R <- Photo.R %>%
  mutate_if(sapply(., is.character), as.factor)
View(Photo.R)
```


```{r}
#make the blank column a factor
Photo.R$BLANK<-ifelse(Photo.R$treatment=='blank', 1,0)
Photo.R$BLANK<-as.factor(Photo.R$BLANK)
View(Photo.R)

photo.blnk <- aggregate(umol.sec ~ species*temp.Cat*light_dark*run*BLANK, data=Photo.R, mean)
View(photo.blnk)
# pull out only the blanks
#photo.blnk<-photo.blnk[photo.blnk$Species=='BK',]
photo.blnk<-photo.blnk[photo.blnk$BLANK==1,]
# remove the species column and join with the full data set
photo.blnk$species<-NULL
# remove the blank column
photo.blnk$BLANK<-NULL

colnames(photo.blnk)[4]<-'blank.rate' # rename the blank rate 

#write.csv(photo.blnk,"C:/Github/TPC_BDA_github/R_output/Manuscript/photo.blk.csv") 

# join the blank data with the rest of the data
Photo.R<-left_join(Photo.R, photo.blnk)
View(Photo.R)

#write.csv(Photo.R,"C:/Github/TPC_BDA_github/R_output/Manuscript/Photo.R_blnk.csv") 

```

```{r}
# subtract the blanks######################
Photo.R$umol.sec.corr<-Photo.R$umol.sec-Photo.R$blank.rate

View(Photo.R)

#### Normalize to SA (surface area)#####

Photo.R$umol.cm2.hr <- (Photo.R$umol.sec.corr*3600)/Photo.R$surf.area.cm2 #mmol cm-2 hr-1

#Photo.R<-Photo.R[complete.cases(Photo.R),] # remove NAs and blanks
Photo.R<-Photo.R[Photo.R$BLANK==0,]
Photo.R <- na.omit(Photo.R)
```

```{r}

#Calculate net P and R
#make ifelse statements to assign light treatments as NP and dark treatments as resp
#light will be assigned NP for net photosynthesis 

Photo.R$rate.type <-ifelse(Photo.R$light_dark=='light', "NP", "R")
Photo.R$rate.type<-as.factor(Photo.R$rate.type)
View(Photo.R)

#rename coral ID
Photo.R$individual.ID <- str_split(Photo.R$fragment.ID, "D", n = Inf, simplify = TRUE)[,1]

Photo.R$individual.ID <- as.factor(Photo.R$individual.ID)

Photo.R$individual.ID<-str_sub(Photo.R$individual.ID , 1, str_length(Photo.R$individual.ID)-1)

#write.csv(Photo.R,"C:/Github/TPC_BDA_github/R_output/Manuscript/Photo.RNP_R.csv")

```

Calculate GP

```{r}

Pnet<-subset(Photo.R,rate.type=="NP")%>%
  dplyr::select(temp.Cat,treatment, genotype,fragment.ID, species,umol.cm2.hr,rate.type, chamber.channel, run, individual.ID)

Rdark<-subset(Photo.R,rate.type=="R")%>%
  dplyr::select(temp.Cat,treatment, genotype,fragment.ID, species,umol.cm2.hr,rate.type, chamber.channel, run, individual.ID)

#Temps<-Photo.R%>%
#  dplyr::select(temp.Cat,treatment, genotype,fragment.ID, #species,umol.cm2.hr,rate.type, Temp.C, chamber.channel, #run, individual.ID)

library(Rmisc)
sumE = summarySE(Photo.R,
                measurevar="Temp.C",            groupvars=c("run","individual.ID"))
Temp.C<-sumE$Temp.C
# average Temp.C for both trials and add to dataframes

#Calculate GP

Pnet$NP<-Pnet$umol.cm2.hr
Pnet$umol.cm2.hr=NULL
Pnet$rate.type=NULL
Pnet[["Temp.C"]] <- Temp.C


Rdark$R<-Rdark$umol.cm2.hr
Rdark$rate.type=NULL
Rdark$umol.cm2.hr=NULL
Rdark[["Temp.C"]] <- Temp.C


Photo.RGP<-left_join(Pnet,Rdark)
View(Photo.RGP)
#Data was not measured correctly for the 2602 dark Trial in the BLANK CHamber- 
#remove trial 2602D 
library(magrittr)
Photo.RGP%<>%
  dplyr::filter(run!="2602")
View(Photo.RGP)  

#(respiration is negative so Pnet-Res=GP)
photo.GP <- Photo.RGP %>%
  group_by(fragment.ID) %>%
  mutate(GP = NP-R)

## Find any negative NP's and make them 0's
lessthan <- which(photo.GP$GP < 0)
photo.GP$GP[lessthan] <- 0
View(photo.GP)
#rearrange columns
photo.GP<- photo.GP[c(1,2,3,4,5,6,7,8,10,9,11,12)]

data_long <- gather(photo.GP, rate.type, umol.cm2.hr, NP:GP, factor_key=TRUE)
View(data_long)

#write.csv(photo.GP,"C:/Github/TPC_BDA_github/R_output/Manuscript/Photo.RNP_R_GP.csv")
```


## isolate GP and R and log values 
```{r}
mydata<-data_long

mydata<-filter(mydata, rate.type !="NP") 

mydataP<-subset(mydata,rate.type=="GP")
mydataR<-subset(mydata,rate.type=="R")

#Take absolute values of Respiration to log it, then combine dataframes and log both R and GP
mydataR$umol.cm2.hr<-abs(mydataR$umol.cm2.hr)
mydata<-rbind(mydataP,mydataR)

mydata$log.rate <- log(mydata$umol.cm2.hr + 1) 

mydata$Temp.C<-as.numeric(as.character(mydata$Temp.C))

mydata<-mydata%>%
  plyr::mutate(K=mydata$Temp.C + 273.15)

mydata$temp.Cat<-factor(mydata$temp.Cat)

#save
#write.csv(mydata,"C:/Github/TPC_BDA_github/R_output/Manuscript/mydata_log.csv")
```


```{r}

rawslope<- ggplot(mydata, aes(x=Temp.C, y=log.rate, group=treatment, color=treatment)) + 
  geom_smooth(se=TRUE, span= 1.5) +
  geom_point(size=2,position=position_dodge(0.5))+
  #geom_errorbar(aes(ymin=PR-sd, ymax=PR+sd), width=.2,
              # position=position_dodge(0.5))+
  labs(y="log.rate", x = "Temperature (ºC)")+
  theme_classic() +
  scale_color_manual(values=c('maroon','magenta'))+
  facet_wrap(~rate.type)
rawslope


GP<-ggplot(mydata, aes(x=Temp.C, y=log.rate, col = species))+
  geom_point()+ 
  geom_smooth(se=TRUE, span= 1.5)+ 
  theme_classic () +
  ylim(-2,4)+  
  facet_wrap(~ species*treatment*rate.type, labeller = labeller(.multi_line = FALSE))
GP
```

```{r}
#Calculate means from resp.datafin with ALL NP, R, and GP umo.cm2.hr on it
AllMeansS <- ddply(photo.GP, c('species'), summarise,
                   #pnet
                   Pnet.mean= mean(NP, na.rm=T), #mean pnet
                   N = sum(!is.na(NP)), # sample size
                   Pnet.se = sd(NP, na.rm=T)/sqrt(N), #SE
                   #Rdark
                   Rdark.mean= mean(R, na.rm=T), #mean rdark
                   Rdark.se = sd(R, na.rm=T)/sqrt(N), #SE
                   #Pgross
                   Pgross.mean  = mean(GP, na.rm=TRUE),
                   Pgross.se = sd(GP, na.rm=TRUE)/sqrt(N),
                   Temp.mean = mean(Temp.C, na.rm=TRUE),
                   Temp.se = sd(Temp.C,na.rm=TRUE)/sqrt(N)
)

View(AllMeansS)

AllMeansT <- ddply(photo.GP, c('treatment'), summarise,
                   #pnet
                   Pnet.mean= mean(NP, na.rm=T), #mean pnet
                   N = sum(!is.na(NP)), # sample size
                   Pnet.se = sd(NP, na.rm=T)/sqrt(N), #SE
                   #Rdark
                   Rdark.mean= mean(R, na.rm=T), #mean rdark
                   Rdark.se = sd(R, na.rm=T)/sqrt(N), #SE
                   #Pgross
                   Pgross.mean  = mean(GP, na.rm=TRUE),
                   Pgross.se = sd(GP, na.rm=TRUE)/sqrt(N),
                   Temp.mean = mean(Temp.C, na.rm=TRUE),
                   Temp.se = sd(Temp.C,na.rm=TRUE)/sqrt(N)
)

View(AllMeansT)

#write.csv(AllMeansT,"C:/Github/TPC_BDA_github/R_output/Manuscript/AllMeansT.csv")
#write.csv(AllMeansS,"C:/Github/TPC_BDA_github/R_output/Manuscript/AllMeansS.csv")
```

