---
title: "PI_Curves_BDA"
author: "Gould, Katelyn"
date: "5/2/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
## install packages if you dont already have them in your library
if ("devtools" %in% rownames(installed.packages()) == 'FALSE') install.packages('devtools') 
library('devtools')
if ("segmented" %in% rownames(installed.packages()) == 'FALSE') install.packages('segmented') 
if ("plotrix" %in% rownames(installed.packages()) == 'FALSE') install.packages('plotrix') 
if ("gridExtra" %in% rownames(installed.packages()) == 'FALSE') install.packages('gridExtra') 
if ("LoLinR" %in% rownames(installed.packages()) == 'FALSE') install_github('colin-olito/LoLinR') 
if ("lubridate" %in% rownames(installed.packages()) == 'FALSE') install.packages('lubridate') 
if ("chron" %in% rownames(installed.packages()) == 'FALSE') install.packages('chron') 
if ("plyr" %in% rownames(installed.packages()) == 'FALSE') install.packages('plyr') 
if ("tidyverse" %in% rownames(installed.packages()) == 'FALSE') install.packages('tidyverse') 


#Read in required libraries
##### Include Versions of libraries
#install_github('colin-olito/LoLinR')
library("ggplot2")
library("segmented")
library("plotrix")
library("gridExtra")
library("LoLinR")
library("lubridate")
library("chron")
library('plyr')
library('tidyverse')
library(tidyr)
library(magrittr)
library(dplyr)
library(esquisse)
library(rvg)
```

```{r}

# get the file path

setwd("C:/Github/TPC_BDA_github")
getwd()

path.p<-"C:/Github/TPC_BDA_github/PI_Curves/Raw_PI" #the location of all your respirometry files

# bring in the respiration files
file.names<-basename(list.files(path = path.p, pattern = "csv$", recursive = TRUE)) #list all csv file names in the folder and subfolders

#basename above removes the subdirectory name from the file
file.names.full<-list.files(path = path.p, pattern = "csv$", recursive = TRUE) 

#generate a 3 column dataframe with specific column names
Photo.R<- data.frame(matrix(NA, nrow=length(file.names)*2, ncol=4))
colnames(Photo.R) <- c("fragment.ID.full","Intercept", "umol.L.sec","Temp.C")
View(Photo.R)
```

if in excel convert to csv file
```{r}
#kate_files <- list.files("C:/Users/Kate/OneDrive - #University of North Carolina at Chapel Hill/June #2019/kate/all", pattern="*.xlsx", full.names=TRUE)
#
#for (all in kate_files){
#  
#  n <- strsplit(all,"C:/Users/Kate/OneDrive - University #of North Carolina at Chapel Hill/June #2019/kate/all")[[1]][2]
#  n <- paste(strsplit(n,"\\.")[[1]][1],".csv", sep = "")
#  df<-read.xlsx(all, sheetIndex = 1)
#  write.csv(df, paste("C:/Users/Kate/OneDrive - University #of North Carolina at Chapel Hill/June 2019/kate/csv",n, #sep = ""), 
#            row.names = FALSE, quote=FALSE)
#}
#
```

```{r}
#Load Sample Info 

Sample.Info <- read.csv("C:/Github/TPC_BDA_github/PI_Curves/PI_RawData/Sample.info.PI.csv")
View(Sample.Info)

# load surface area data
SA <- read.csv("C:/Github/TPC_BDA_github/PI_Curves/PI_RawData/SA_PI.csv") #read sample.info data
View(SA)
```

```{r}
#Calculate the volume of water
as.numeric(SA$volume.mls)
# joint the sample info and surface area and volume measurements
Sample.Info<-left_join(Sample.Info, SA)
Sample.Info$date<-NULL

View(Sample.Info)
```

```{r}
# for every file in list calculate O2 uptake or release rate and add the data to the Photo.R dataframe
for(i in 1:length(file.names.full)) { # for every file in list calculate O2 uptake or release rate and add the data to the Photo.R dataframe
  
  #find the lines in sample info that have the same file name that is being brought it
  FRow<-which(Sample.Info$fragment.ID.full==strsplit(file.names[i],'.csv'))
  # read in the O2 data one by one
  Photo.Data1 <-read.csv(file.path(path.p,file.names.full[i]), header=T) # skips the first line
  Photo.Data1 <-plyr::rename(Photo.Data1, c("Date"="Time","Oxygen"= "Value","Temperature"="Temp"))
  #rename columns 
  Photo.Data1  <- Photo.Data1[,c("Time","Value","Temp")] #subset columns of interest
  # Photo.Data1$Time <-strptime(Photo.Data1$Time, format = "%H:%M:%S") 
  Photo.Data1$Time <- strftime(Photo.Data1$Time, format = "%H:%M:%S") 
  #Photo.Data1$Time <- as.POSIXct(Photo.Data1$Time,format="%H:%M:%S", tz = "") #convert time from character to time
  Photo.Data1 <- na.omit(Photo.Data1)
  
  
  # clean up some of the data
  n<-dim(Photo.Data1)[1] # length of full data
  Photo.Data1 <-Photo.Data1[240:(n-3),] #start at data point ~4 minute in to avoid excess noise from start of run and remove last 3 lines containing text
  n<-dim(Photo.Data1)[1] #list length of trimmed data
  Photo.Data1$sec <- (1:n) #set seconds by one from start to finish of run in a new column
  
  
  #Save plot prior to and after data thinning to make sure thinning is not too extreme
  rename <- sub(".csv","", file.names[i]) # remove all the extra stuff in the file name
  
  #pdf(paste0("C:/Users/gould054/Documents/TPC_BDA/AllDataAnalysis_Presens_TPC_params/TPC_params_estimates_Topt/Output",rename,"thinning.pdf")) # open the graphics device
  pdf(paste0("C:/Github/TPC_BDA_github/PI_Curves/PI_output_thinned",rename,"thinning.pdf")) # open the graphics device
  
  par(omi=rep(0.3, 4)) #set size of the outer margins in inches
  par(mfrow=c(1,2)) #set number of rows and columns in multi plot graphic
  plot(Value ~ sec, data=Photo.Data1 , xlab='Time (seconds)', ylab=expression(paste(' O'[2],' (',mu,'mol/L)')), type='n', axes=FALSE) #plot (empty plot to fill) data as a function of time
  usr  <-  par('usr') # extract the size of the figure margins
  rect(usr[1], usr[3], usr[2], usr[4], col='grey90', border=NA) # put a grey background on the plot
  whiteGrid() # make a grid
  box() # add a box around the plot
  points(Photo.Data1 $Value ~ Photo.Data1 $sec, pch=16, col=transparentColor('dodgerblue2', 0.6), cex=1.1)
  axis(1) # add the x axis
  axis(2, las=1) # add the y-axis
  
  # Thin the data to make the code run faster
  Photo.Data.orig<-Photo.Data1#save original unthinned data
  Photo.Data1 <-  thinData(Photo.Data1 ,by=20)$newData1 #thin data by every 20 points for all the O2 values
  Photo.Data1$sec <- as.numeric(rownames(Photo.Data1 )) #maintain numeric values for time
  Photo.Data1$Temp<-NA # add a new column to fill with the thinned data
  Photo.Data1$Temp <-  thinData(Photo.Data.orig,xy = c(1,3),by=20)$newData1[,2] #thin data by every 20 points for the temp values
  
  # plot the thinned data
  plot(Value ~ sec, data=Photo.Data1 , xlab='Time (seconds)', ylab=expression(paste(' O'[2],' (',mu,'mol/L)')), type='n', axes=FALSE) #plot thinned data
  usr  <-  par('usr')
  rect(usr[1], usr[3], usr[2], usr[4], col='grey90', border=NA)
  whiteGrid()
  box()
  points(Photo.Data1 $Value ~ Photo.Data1 $sec, pch=16, col=transparentColor('dodgerblue2', 0.6), cex=1.1)
  axis(1)
  axis(2, las=1)
  ##Olito et al. 2017: It is running a bootstrapping technique and calculating the rate based on density
  #option to add multiple outputs method= c("z", "eq", "pc")
  Regs  <-  rankLocReg(xall=Photo.Data1$sec, yall=Photo.Data1$Value, alpha=0.5, method="pc", verbose=TRUE)  
  
  # add the regression data
  plot(Regs)
  dev.off()
  
  # fill in all the O2 consumption and rate data
  Photo.R[i,2:3] <- Regs$allRegs[1,c(4,5)] #inserts slope and intercept in the dataframe
  Photo.R[i,1] <- rename #stores the file name in the Date column
  Photo.R[i,4] <- mean(Photo.Data1$Temp, na.rm=T)  #stores the Temperature in the Temp.C column
  #Photo.R[i,5] <- PR[j] #stores stores whether it is photosynthesis or respiration
  
  
  # rewrite the file everytime... I know this is slow, but it will save the data that is already run
}
```

```{r}
View(Photo.R)

  
Photo.R <- na.omit(Photo.R)
  
#write.csv(Photo.R,"C:/Github/TPC_BDA_github/PI_Curves/PI_output/Photo.R.csv") 
```

```{r}

#join dataframes
Photo.R<-left_join(Photo.R, Sample.Info)
View(Photo.R)
```

```{r}
#Convert sample volume to mL
Photo.R$volume <- Photo.R$volume.mls/1000 #calculate volume

#Account for chamber volume to convert from umol L-1 s-1 to umol s-1. This standardizes across water volumes (different because of coral size) and removes per Liter
Photo.R$umol.sec <- Photo.R$umol.L.sec*Photo.R$volume

#convert character columns to factors
Photo.R <- Photo.R %>%
  mutate_if(sapply(., is.character), as.factor)
View(Photo.R)

# subtract the blanks######################
Photo.R$umol.sec.corr<-Photo.R$umol.sec

#### Normalize to organic biomass= Surface area (based on Image J analysis )#####
Photo.R$umol.cm2.hr <- (Photo.R$umol.sec.corr*3600)/Photo.R$surf.area.cm2 #mmol cm-2 hr-1

# log the rates
Photo.R$Rate.ln<-log(Photo.R$umol.cm2.hr+0.1)

write.csv(Photo.R,"C:/Github/TPC_BDA_github/PI_Curves/PI_output/Photo.Rlog.csv") 
```

```{r}
ggplot(Photo.R, aes(x=run, y=Rate.ln,  group=c(species), col = fragment.ID))+
geom_point(aes(shape=treatment), position = position_dodge(width = 0.2), size=4)+  
facet_wrap(~ species*treatment, labeller = labeller(.multi_line = FALSE))

PIcurve<-ggplot(Photo.R, aes(x=avgPAR, y=Rate.ln,  group=c(species), col = fragment.ID))+
  geom_point(aes(shape=treatment), position = position_dodge(width = 0.2), size=4) +
  facet_wrap(~ species, labeller = labeller(.multi_line = FALSE))
PIcurve


rawslope<- ggplot(Photo.R, aes(x=avgPAR, y=Rate.ln, group=treatment, color=treatment)) + 
  geom_smooth(se=TRUE, span= 1.5) +
  geom_point(size=2,position=position_dodge(0.5))+
  #geom_errorbar(aes(ymin=PR-sd, ymax=PR+sd), width=.2,
              # position=position_dodge(0.5))+
  labs(y="log.rate", x = "Temperature (ºC)")+
  theme_classic() +
  scale_color_manual(values=c('maroon','magenta'))+
  facet_wrap(~species)
rawslope

```


```{r}

PhotoMeans<- Photo.R %>%
  group_by(treatment, run)%>%
  summarise(rates.mean = mean(umol.cm2.hr), se = sd(umol.cm2.hr)/sqrt(n()))
View(PhotoMeans)

#write.csv(PhotoMeans,"C:/Github/TPC_BDA_github/PI_Curves/PI_output/Photo.MeanCurveRates.csv") 
```



```{r}
# plot the raw data with the means on top
ggplot()+
theme_bw()+  
  geom_point(data=Photo.R, aes(x=run, y=umol.cm2.hr, shape=treatment, col = genotype), position = position_dodge(width = 0.2), size=4)+
  geom_point(data=PhotoMeans, aes(x=run, y=rates.mean),  size=1)+
  geom_line(data = PhotoMeans,  aes(x=run, y=rates.mean), size=1)+
  geom_errorbar(data = PhotoMeans, aes(x = run, ymin=rates.mean-se, ymax=rates.mean+se, width=.2))+
  facet_wrap(~ treatment, labeller = labeller(.multi_line = FALSE))

```


